version: '2'
services:

    # Your existing service containers
    my_service:
        image: nginx:alpine
        volumes:
            - my_service_config:/etc/nginx
            - my_service_data:/var/www/html

    # The Syncthing container
    syncthing:
        image: sebble/syncthing-mirror
        restart: always

        # Map your existing volumes into Syncthing
        volumes:
            - my_service_config:/root/Sync/my_service_config
            - my_service_data:/root/Sync/my_service_data

        # By default "/root/Sync" will be shared read-only with this device
        environment:
            - REMOTE_DEVICE_ID=1234567-ABCDEFG-1234567-ABCDEFG-1234567-ABCDEFG-1234567-ABCDEFG

        # Syncthing uses the hostname to identify this device
        hostname: my_service-syncthing

        # Optionally, expose the Syncthing web interface
        #ports:
        #    - "8080:80"

# Your existing container volumes
volumes:
    my_service_config: {}
    my_service_data: {}
