version: '2'
services:

    hosts:
        build: .
        image: sebble/hosts
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/hosts:/hosts
        environment:
            - HOSTS_FILE=/hosts
        restart: always
